-- 제때 — 프리셋 카탈로그 159종
--
-- 이 파일은 손으로 고치지 않는다. data/jettae_catalog.json 이 원본이고,
-- `npm run seed:sql` (scripts/gen-catalog-sql.mjs)이 이 파일을 다시 만든다.
--
-- 등록이 2초가 되려면 "품목 → 권장 주기"가 이미 있어야 한다.
-- 이 카탈로그의 품질이 곧 제품의 품질이다.

insert into catalog
  (code, name, zone, input_type, metric, cycle_days, cycle_usage, unit, season,
   safety_locked, onboarding_pick, note)
values
  ('bath_toothbrush', '칫솔', '욕실', 'list', 'time', 90, null, null, 'all', false, true, '칫솔모가 벌어지면 플라그 제거력 저하. 마모 시 조기 교체'),
  ('bath_ebrush_head', '전동칫솔 브러시헤드', '욕실', 'list', 'time', 90, null, null, 'all', false, false, '수동 칫솔과 동일 기준'),
  ('bath_interdental', '치간칫솔', '욕실', 'list', 'time', 7, null, null, 'all', false, false, '모가 휘면 즉시 교체'),
  ('bath_tongue', '혀클리너', '욕실', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('bath_razor', '면도날', '욕실', 'list', 'time', 21, null, null, 'all', false, true, '사용 5~10회 기준, 매일 면도 시 약 2~3주'),
  ('bath_showertowel', '샤워타월(때수건)', '욕실', 'list', 'time', 60, null, null, 'all', false, true, '습한 환경에서 세균 번식. 2개월 권장'),
  ('bath_towel', '수건', '욕실', 'list', 'time', 730, null, null, 'all', false, false, '2년. 뻣뻣해지면 조기 교체'),
  ('bath_bathmat_wash', '욕실 발매트 세탁', '욕실', 'list', 'time', 14, null, null, 'all', false, false, null),
  ('bath_slipper', '욕실 슬리퍼', '욕실', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('bath_drain_net', '배수구 거름망', '욕실', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('bath_toiletbrush', '변기솔', '욕실', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('bath_curtain_wash', '샤워커튼 세탁', '욕실', 'list', 'time', 30, null, null, 'all', false, false, '곰팡이 발생 전 주기적 세탁'),
  ('bath_soapnet', '비누 거품망', '욕실', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('bath_cup_clean', '양치컵·칫솔꽂이 세척', '욕실', 'list', 'time', 14, null, null, 'all', false, false, '바닥 물때가 세균 온상'),
  ('bath_toothpaste', '치약 (개봉 후)', '욕실', 'pao', 'time', 365, null, null, 'all', false, false, '개봉 후 1년'),
  ('bath_mouthwash', '구강청결제 (개봉 후)', '욕실', 'pao', 'time', 180, null, null, 'all', false, false, null),
  ('bath_hairbrush_clean', '헤어브러시 세척', '욕실', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('bath_hairbrush', '헤어브러시 교체', '욕실', 'list', 'time', 365, null, null, 'all', false, false, null),
  ('bath_mold_clean', '욕실 곰팡이 청소', '욕실', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('bath_showerhead_clean', '샤워기 헤드 세척', '욕실', 'list', 'time', 90, null, null, 'all', false, false, '구연산 세척. 부품 교체 아님'),
  ('bath_sponge', '목욕 스펀지', '욕실', 'list', 'time', 60, null, null, 'all', false, false, null),
  ('bath_nailclipper', '손톱깎이 소독', '욕실', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('kit_sponge', '수세미', '주방', 'list', 'time', 30, null, null, 'all', false, true, '젖은 수세미는 세균 다수. 1개월 권장'),
  ('kit_dishcloth', '행주', '주방', 'list', 'time', 30, null, null, 'all', false, true, '삶거나 교체'),
  ('kit_gloves', '고무장갑', '주방', 'list', 'time', 30, null, null, 'all', false, true, '1개월 권장'),
  ('kit_board_plastic', '도마 (플라스틱)', '주방', 'list', 'time', 365, null, null, 'all', false, false, '칼자국 홈에 세균. 1년 권장'),
  ('kit_board_wood', '도마 (나무)', '주방', 'list', 'time', 365, null, null, 'all', false, false, null),
  ('kit_pan_coated', '프라이팬 (코팅)', '주방', 'list', 'time', 730, null, null, 'all', false, false, '코팅 벗겨지면 즉시 교체'),
  ('kit_knife_sharpen', '칼 연마', '주방', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('kit_wood_utensil', '나무 수저·주걱', '주방', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('kit_silicone', '실리콘 조리도구', '주방', 'list', 'time', 365, null, null, 'all', false, false, null),
  ('kit_container', '플라스틱 밀폐용기', '주방', 'list', 'time', 90, null, null, 'all', false, false, '흠집·변색 시 교체. 3개월 이상 권장하지 않음'),
  ('kit_container_seal', '밀폐용기 패킹', '주방', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('kit_tumbler_seal', '텀블러 패킹', '주방', 'list', 'time', 180, null, null, 'all', false, false, '패킹 틈이 곰팡이 발생 지점'),
  ('kit_sink_net', '싱크대 배수구망', '주방', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('kit_foodbin_clean', '음식물 쓰레기통 세척', '주방', 'list', 'time', 7, null, null, 'all', false, false, null),
  ('kit_fridge_deo', '냉장고 탈취제', '주방', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('kit_fridge_clean', '냉장고 청소', '주방', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('kit_kettle_clean', '전기포트 세척', '주방', 'list', 'time', 90, null, null, 'all', false, false, '구연산 세척'),
  ('kit_coffee_clean', '커피머신 세척', '주방', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('kit_grinder_clean', '커피 그라인더 청소', '주방', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('kit_oil', '식용유 (개봉 후)', '주방', 'pao', 'time', 90, null, null, 'all', false, false, '산패 주의'),
  ('kit_sesame', '참기름·들기름 (개봉 후)', '주방', 'pao', 'time', 60, null, null, 'all', false, false, '산패가 빠름. 냉장 보관 권장'),
  ('kit_soy', '간장 (개봉 후)', '주방', 'pao', 'time', 180, null, null, 'all', false, false, null),
  ('kit_paste', '고추장·된장 (개봉 후)', '주방', 'pao', 'time', 180, null, null, 'all', false, false, null),
  ('kit_sauce', '케첩·마요네즈 (개봉 후)', '주방', 'pao', 'time', 60, null, null, 'all', false, false, '마요네즈는 개봉 후 냉장 1~2개월'),
  ('kit_spice', '가루 조미료 (개봉 후)', '주방', 'pao', 'time', 365, null, null, 'all', false, false, null),
  ('kit_towelholder', '키친타월 홀더 청소', '주방', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('kit_cutlery_clean', '수저통 세척', '주방', 'list', 'time', 14, null, null, 'all', false, false, '바닥 고인 물이 문제'),
  ('kit_mat_wash', '주방 매트 세탁', '주방', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('kit_apron_wash', '앞치마 세탁', '주방', 'list', 'time', 14, null, null, 'all', false, false, null),
  ('kit_trivet', '냄비받침', '주방', 'list', 'time', 365, null, null, 'all', false, false, null),
  ('bed_sheet_wash', '침구 세탁 (시트·커버)', '침실', 'list', 'time', 14, null, null, 'all', false, true, '2주 권장. 땀·각질 축적'),
  ('bed_pillow', '베개', '침실', 'list', 'time', 540, null, null, 'all', false, false, '18개월 권장'),
  ('bed_pillow_wash', '베개 세탁', '침실', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('bed_pillowcase_wash', '베갯잇 세탁', '침실', 'list', 'time', 7, null, null, 'all', false, true, '얼굴이 닿는 면. 주 1회'),
  ('bed_duvet_wash', '이불 세탁', '침실', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('bed_mattress', '매트리스', '침실', 'list', 'time', 2920, null, null, 'all', false, false, '약 8년'),
  ('bed_mattress_cover', '매트리스 커버 세탁', '침실', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('bed_mattress_flip', '매트리스 회전', '침실', 'list', 'time', 90, null, null, 'all', false, false, '눌림 방지'),
  ('bed_blanket_wash', '담요 세탁', '침실', 'list', 'time', 60, null, null, 'all', false, false, null),
  ('bed_pajama_wash', '잠옷 세탁', '침실', 'list', 'time', 7, null, null, 'all', false, false, null),
  ('bed_eyemask', '안대 세탁', '침실', 'list', 'time', 14, null, null, 'all', false, false, null),
  ('bed_curtain_wash', '커튼 세탁', '침실', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('bed_rug_wash', '러그·카펫 세탁', '침실', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('bed_electricmat', '전기장판 점검', '침실', 'list', 'time', 365, null, null, 'winter', false, false, '겨울 시작 시 전선 피복 확인'),
  ('bed_humidifier_clean', '가습기 세척', '침실', 'list', 'time', 7, null, null, 'winter', false, false, '세균 번식 빠름. 주 1회 이상'),
  ('bed_underbed_clean', '침대 밑 청소', '침실', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('liv_vac_bag', '청소기 먼지봉투', '거실', 'list', 'time', 30, null, null, 'all', false, false, '기종별 규격 상이'),
  ('liv_vac_head', '청소기 헤드 청소', '거실', 'list', 'time', 30, null, null, 'all', false, false, '머리카락 엉킴 제거'),
  ('liv_vac_battery', '무선청소기 배터리', '거실', 'list', 'time', 1095, null, null, 'all', false, false, '약 3년. 사용 시간 절반으로 줄면 교체'),
  ('liv_mop_pad', '물걸레 패드', '거실', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('liv_wipe_sheet', '청소포 재고 확인', '거실', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('liv_mop', '밀대 걸레', '거실', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('liv_bin_clean', '쓰레기통 세척', '거실', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('liv_sofa_cover', '소파 커버 세탁', '거실', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('liv_cushion_cover', '쿠션 커버 세탁', '거실', 'list', 'time', 60, null, null, 'all', false, false, null),
  ('liv_blind_clean', '블라인드 청소', '거실', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('liv_screen_clean', '방충망 청소', '거실', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('liv_window_clean', '창틀 청소', '거실', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('liv_remote_battery', '리모컨 건전지', '거실', 'list', 'time', 365, null, null, 'all', false, false, null),
  ('liv_clock_battery', '벽시계 건전지', '거실', 'list', 'time', 365, null, null, 'all', false, false, null),
  ('liv_doorlock_battery', '도어락 건전지', '거실', 'list', 'time', 180, null, null, 'all', false, false, '방전되면 문이 안 열린다'),
  ('liv_diffuser', '방향제·디퓨저', '거실', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('liv_dehumidifier', '제습제', '거실', 'list', 'time', 60, null, null, 'summer', false, false, '장마철 교체 주기 단축'),
  ('liv_mothball', '옷장 방충제', '거실', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('liv_plant_water', '화분 물주기', '거실', 'list', 'time', 7, null, null, 'all', false, false, '식물 종류에 따라 조정'),
  ('liv_plant_repot', '화분 분갈이', '거실', 'list', 'time', 730, null, null, 'all', false, false, null),
  ('liv_fan_clean', '선풍기 청소', '거실', 'list', 'time', 30, null, null, 'summer', false, false, '여름 시즌에만 카운트'),
  ('liv_light_clean', '조명 청소', '거실', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('liv_shoe_deo', '신발장 탈취제', '거실', 'list', 'time', 90, null, null, 'all', false, false, null),
  ('per_lens_daily', '콘택트렌즈 (원데이)', '미용', 'list', 'time', 1, null, null, 'all', false, false, '재사용 금지'),
  ('per_lens_2week', '콘택트렌즈 (2주용)', '미용', 'list', 'time', 14, null, null, 'all', false, false, '착용 횟수 기준은 Phase 4'),
  ('per_lens_month', '콘택트렌즈 (한달용)', '미용', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('per_lens_case', '렌즈 케이스', '미용', 'list', 'time', 90, null, null, 'all', false, true, '3개월 권장. 세균 감염 위험'),
  ('per_lens_solution', '렌즈 세척액 (개봉 후)', '미용', 'pao', 'time', 90, null, null, 'all', false, false, '개봉 후 3개월'),
  ('per_glasses_check', '안경 나사·코받침 점검', '미용', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('per_sunscreen', '선크림 (개봉 후)', '미용', 'pao', 'time', 365, null, null, 'all', false, true, 'PAO 표기 우선. 보통 12M'),
  ('per_foundation', '파운데이션 (개봉 후)', '미용', 'pao', 'time', 365, null, null, 'all', false, false, '보통 12M'),
  ('per_cushion', '쿠션팩트 (개봉 후)', '미용', 'pao', 'time', 365, null, null, 'all', false, false, '퍼프는 별도 교체'),
  ('per_mascara', '마스카라 (개봉 후)', '미용', 'pao', 'time', 120, null, null, 'all', false, true, '3~6개월. 눈 감염 위험으로 가장 짧음'),
  ('per_eyeliner', '아이라이너 (개봉 후)', '미용', 'pao', 'time', 180, null, null, 'all', false, false, '리퀴드 기준'),
  ('per_eyeshadow', '아이섀도 (개봉 후)', '미용', 'pao', 'time', 730, null, null, 'all', false, false, '파우더 제형은 상대적으로 김'),
  ('per_lipstick', '립스틱 (개봉 후)', '미용', 'pao', 'time', 545, null, null, 'all', false, false, '약 18개월'),
  ('per_lipbalm', '립밤 (개봉 후)', '미용', 'pao', 'time', 365, null, null, 'all', false, false, null),
  ('per_toner', '스킨·토너 (개봉 후)', '미용', 'pao', 'time', 365, null, null, 'all', false, false, null),
  ('per_lotion', '로션·에멀전 (개봉 후)', '미용', 'pao', 'time', 365, null, null, 'all', false, false, null),
  ('per_serum', '에센스·세럼 (개봉 후)', '미용', 'pao', 'time', 180, null, null, 'all', false, false, null),
  ('per_eyecream', '아이크림 (개봉 후)', '미용', 'pao', 'time', 180, null, null, 'all', false, false, null),
  ('per_vitc', '비타민C 세럼 (개봉 후)', '미용', 'pao', 'time', 90, null, null, 'all', false, false, '산화가 빠른 액티브 성분'),
  ('per_retinol', '레티놀 (개봉 후)', '미용', 'pao', 'time', 180, null, null, 'all', false, false, '빛·공기에 불안정'),
  ('per_cleanser', '클렌징폼 (개봉 후)', '미용', 'pao', 'time', 365, null, null, 'all', false, false, null),
  ('per_cleansing_oil', '클렌징 오일 (개봉 후)', '미용', 'pao', 'time', 365, null, null, 'all', false, false, null),
  ('per_perfume', '향수 (개봉 후)', '미용', 'pao', 'time', 1095, null, null, 'all', false, false, '약 3년. 직사광선 피할 것'),
  ('per_nail', '네일 폴리시 (개봉 후)', '미용', 'pao', 'time', 730, null, null, 'all', false, false, null),
  ('per_brush_clean', '메이크업 브러시 세척', '미용', 'list', 'time', 14, null, null, 'all', false, false, '2주 권장. 세균·트러블 원인'),
  ('per_brush', '메이크업 브러시 교체', '미용', 'list', 'time', 730, null, null, 'all', false, false, null),
  ('per_puff', '퍼프·스펀지', '미용', 'list', 'time', 30, null, null, 'all', false, true, '1개월 권장'),
  ('per_shavecream', '면도크림 (개봉 후)', '미용', 'pao', 'time', 365, null, null, 'all', false, false, null),
  ('per_deodorant', '데오드란트 (개봉 후)', '미용', 'pao', 'time', 365, null, null, 'all', false, false, null),
  ('per_hairdye_check', '염색 주기', '미용', 'list', 'time', 60, null, null, 'all', false, false, '두피 회복 위해 최소 간격 유지'),
  ('hel_supplement', '영양제 (개봉 후)', '건강', 'pao', 'time', 180, null, null, 'all', false, false, '제품 표기 우선'),
  ('hel_probiotic', '유산균 (개봉 후)', '건강', 'pao', 'time', 90, null, null, 'all', false, false, '냉장 보관 제품 다수'),
  ('hel_medicine_check', '상비약 유효기간 점검', '건강', 'list', 'time', 180, null, null, 'all', true, false, '안전 품목 — 주기 자동 조정 제외'),
  ('hel_firstaid_check', '구급상자 점검', '건강', 'list', 'time', 180, null, null, 'all', true, false, '안전 품목 — 주기 자동 조정 제외'),
  ('hel_mask', '마스크 (KF)', '건강', 'list', 'time', 1, null, null, 'all', false, false, '1회용 원칙'),
  ('hel_thermometer_bat', '체온계 건전지', '건강', 'list', 'time', 730, null, null, 'all', false, false, null),
  ('hel_bp_check', '혈압계 점검', '건강', 'list', 'time', 730, null, null, 'all', false, false, null),
  ('hel_sanitizer', '손소독제 (개봉 후)', '건강', 'pao', 'time', 365, null, null, 'all', false, false, '알코올 휘발로 효과 저하'),
  ('hel_bandage_check', '밴드·거즈 점검', '건강', 'list', 'time', 365, null, null, 'all', true, false, '안전 품목 — 주기 자동 조정 제외'),
  ('hel_heatpack_check', '찜질팩 점검', '건강', 'list', 'time', 365, null, null, 'winter', false, false, null),
  ('saf_smoke_battery', '화재감지기 건전지', '안전', 'list', 'time', 365, null, null, 'all', true, false, '권장 주기 고수 — 자동 조정 제외'),
  ('saf_smoke_unit', '화재감지기 본체', '안전', 'list', 'time', 3650, null, null, 'all', true, false, '내용연수 10년'),
  ('saf_ext_check', '소화기 압력 점검', '안전', 'list', 'time', 30, null, null, 'all', true, false, '게이지 녹색 범위 확인'),
  ('saf_ext_unit', '소화기 교체', '안전', 'list', 'time', 3650, null, null, 'all', true, false, '내용연수 10년'),
  ('saf_gas_hose', '가스레인지 호스', '안전', 'list', 'time', 1825, null, null, 'all', true, false, '권장 5년'),
  ('saf_breaker_test', '누전차단기 테스트', '안전', 'list', 'time', 30, null, null, 'all', true, false, '월 1회 테스트 버튼'),
  ('saf_powerstrip', '멀티탭 교체', '안전', 'list', 'time', 1095, null, null, 'all', true, false, '약 3년. 변색·발열 시 즉시'),
  ('saf_gas_valve', '가스 밸브 점검', '안전', 'list', 'time', 180, null, null, 'all', true, false, null),
  ('lau_washer_clean', '세탁조 청소', '세탁', 'list', 'time', 60, null, null, 'all', false, true, '2개월 권장. 곰팡이 냄새의 주원인'),
  ('lau_washer_net', '세탁기 거름망 청소', '세탁', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('lau_dryer_lint', '건조기 먼지 제거', '세탁', 'list', 'time', 7, null, null, 'all', false, false, '화재 예방. 매 사용 권장'),
  ('lau_runningshoe', '러닝화', '세탁', 'list', 'usage', 540, 700, 'km', 'all', false, false, '주행거리 기준 — 사용량 기준 품목 (Phase 4)'),
  ('lau_underwear', '속옷', '세탁', 'list', 'time', 365, null, null, 'all', false, false, null),
  ('lau_socks', '양말', '세탁', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('lau_bra', '브래지어', '세탁', 'list', 'time', 270, null, null, 'all', false, false, '약 9개월. 형태 변형 시 교체'),
  ('lau_swimsuit', '수영복', '세탁', 'list', 'time', 365, null, null, 'all', false, false, '염소로 인한 신축성 저하'),
  ('lau_insole', '신발 깔창', '세탁', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('lau_slipper', '실내 슬리퍼', '세탁', 'list', 'time', 365, null, null, 'all', false, false, null),
  ('lau_umbrella_check', '우산 점검', '세탁', 'list', 'time', 365, null, null, 'all', false, false, null),
  ('lau_shoe_clean', '운동화 세탁', '세탁', 'list', 'time', 60, null, null, 'all', false, false, null),
  ('tec_screenfilm', '휴대폰 액정보호필름', '전자', 'list', 'time', 180, null, null, 'all', false, false, null),
  ('tec_phonecase', '휴대폰 케이스', '전자', 'list', 'time', 365, null, null, 'all', false, false, '변색·균열 시 교체'),
  ('tec_eartip', '이어폰 이어팁', '전자', 'list', 'time', 90, null, null, 'all', false, false, '실리콘 변형·귀지 축적'),
  ('tec_cable', '충전 케이블', '전자', 'list', 'time', 365, null, null, 'all', false, false, '피복 벗겨지면 즉시 교체'),
  ('tec_keyboard_clean', '키보드 청소', '전자', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('tec_laptop_clean', '노트북 내부 청소', '전자', 'list', 'time', 365, null, null, 'all', false, false, '팬 먼지 제거'),
  ('tec_backup', '데이터 백업 점검', '전자', 'list', 'time', 30, null, null, 'all', false, false, null),
  ('tec_password', '주요 비밀번호 변경', '전자', 'list', 'time', 180, null, null, 'all', false, false, null)
on conflict (code) do update set
  name            = excluded.name,
  zone            = excluded.zone,
  input_type      = excluded.input_type,
  metric          = excluded.metric,
  cycle_days      = excluded.cycle_days,
  cycle_usage     = excluded.cycle_usage,
  unit            = excluded.unit,
  season          = excluded.season,
  safety_locked   = excluded.safety_locked,
  onboarding_pick = excluded.onboarding_pick,
  note            = excluded.note;
